[package]
name = "serde_yaml-fuzz-bw"
version = "0.0.0"
#authors = ["David Tolnay <dtolnay@gmail.com>"]
authors = ["Bourumir Wyngs <bourumir.wyngs@gmail.com>"]
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_yaml_bw = { path = ".." }

[[bin]]
name = "fuzz_from_slice"
path = "fuzz_targets/fuzz_from_slice.rs"
test = false
doc = false

[workspace]
