name: API compatibility

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  semver:
    name: cargo-semver-checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check public API compatibility
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          baseline-rev: 2.5.0
