name: Daily Fuzz, Nightly Rust Tests, and Audit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allows manual triggering

jobs:
  fuzz_test_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install cargo-fuzz and cargo-audit
        run: |
          cargo install cargo-fuzz
          cargo install cargo-audit

      - name: Run standard tests, taking advantage we now have nightly Rust
        run: cargo test --verbose

      - name: Run cargo audit, taking advantage we now have nightly Rust
        run: cargo audit

      - name: Run fuzz target 'from_slice' (1 min)
        run: cargo fuzz run from_slice -- -max_total_time=60 -rss_limit_mb=1024

      - name: Run fuzz target 'from_reader' (1 min)
        run: cargo fuzz run from_reader -- -max_total_time=60 -rss_limit_mb=1024

      - name: Upload fuzz crash artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: fuzz-crash-artifacts
          path: fuzz/artifacts/