name: Fuzz, Nightly Rust Tests, and Audit

on:
  schedule:
    - cron: '23 5 1,11,21 * *'  # Runs three times a month on the 1st, 11th, and 21st at 00:23 EST (05:23 UTC)
  workflow_dispatch:     # Allows manual triggering

jobs:
  fuzz_test_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust nightly
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install cargo-fuzz and cargo-audit
        run: |
          cargo install cargo-fuzz
          cargo install cargo-audit

      - name: Run standard tests, taking advantage we now have nightly Rust, normally we test with stable
        run: cargo test --verbose

      - name: Run cargo audit, this also makes sense to run periodically
        run: cargo audit

      # It is not long but it will run multiple times automatically
      - name: Run fuzz target 'slice_and_reader' (10 min)
        run: cargo fuzz run slice_and_reader -- -max_total_time=60 -rss_limit_mb=1024 -close_fd_mask=3

      - name: Upload fuzz crash artifacts
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: fuzz-crash-artifacts
          path: fuzz/artifacts/